---

- name: Checkout git repository for dehydrated
  git: repo=https://github.com/lukas2511/dehydrated.git dest={{dehydrated_basedir}} update=yes

- name: Create dehydrated directories
  file: state=directory path={{item}}
  with_items:
    - "{{dehydrated_basedir}}"
    - "{{dehydrated_configdir}}"
    - "{{dehydrated_certsdir}}"
    - "{{dehydrated_accountsdir}}"
    - "{{dehydrated_wellknown}}"

- name: Template dehydrated config files
  template: src="{{item}}.j2" dest="/config/dehydrated/{{item}}" owner=root group=root
  with_items:
    - config
    - domains.txt

- name: Create account key and accept terms
  command: creates="{{dehydrated_accountsdir}}/*/account_key.pem" {{dehydrated_basedir}}/dehydrated --register --accept-terms

- name: Create apache2 config file
  template: src="dehydrated.conf" dest="{{dehydrated_apache2dir}}/conf-available/dehydrated.conf" owner=root group=root mode=0644
  when: dehydrated_apache2|bool

- name: Enable apache2 config
  file: state=link src="{{dehydrated_apache2dir}}/conf-available/dehydrated.conf" dest="{{dehydrated_apache2dir}}/conf-enabled/dehydrated.conf"
  when: dehydrated_apache2_enable|bool
